### ISSUE TITLE
Some things deprecated in iOS 9.0

### ISSUE THREAD

**Issue by matryer** [itsthejb/NSURL-QueryDictionary#12]
<img width="246" alt="screen shot 2016-01-27 at 07 11 37" src="https://cloud.githubusercontent.com/assets/101659/12606415/4f2dfd0a-c4c5-11e5-8365-00efe9f4f691.png">

* `.../Pods/NSURL+QueryDictionary/NSURL+QueryDictionary/NSURL+QueryDictionary.m:65:36: * 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -* stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.`
* `.../Pods/NSURL+QueryDictionary/NSURL+QueryDictionary/NSURL+QueryDictionary.m:72:30: * 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -* stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.`
* `.../Pods/NSURL+QueryDictionary/NSURL+QueryDictionary/NSURL+QueryDictionary.m:117:43: * 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString * stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which * encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).`

**Comment by itsthejb** [comment]
Thanks! Haven't looked at this project for a little while, so not surprised it's got a bit behind. I'll try to update it right now
